### ISSUE TITLE
Detect stateObservable cycles

### ISSUE THREAD

**Issue by skywall** [SumeraMartin/koreactor#9]
Hi, we have run into issue with state updated cyclically in our reactor. Application have not crashed but was freezed instead. Here is sample code:

```
        stateObservable
            .map { it.firstName.isNotEmpty() }
            .map { ChangeSomeStateReducer(it) }
            .bindToView()
```

We listen to state changes, reducer updates it based on an emit and we are in infinite loop. Do you think library can warn us somehow that this is probably happening? 

Thanks in advance.

**Comment by SumeraMartin** [comment]
Hi, the code snippet that you posted here is equivalent of recursion without terminal condition. 

1) You should avoid these situations and instead you should observe only specific actions.
2) If it is not possible or if it would be a very complex to avoid using `stateObservable` then you should use a `getChange()` or  `filter()` methods.
3) If this is still not enough and you really need to make sure that this kind of `recursion` won’t happen then you can count elements and throw an exception if too many elements will be emitted. Somehow like this:
```
safeObservable = stateObservable
.zipWith(Observable.range(0, Integer.MAX_VALUE), (state, counter) -> Pair(state, counter))
.flatMap((state, counter) -> if (counter > 1000) Observable.error("....") else Observable.just(state))
```
This is far from an ideal solution but I don’t see any other way of solving it. This condition might be used only during the development phase and it should be ignored afterward.

Sorry, for the late response.
